# Dockerfile.backend (в корне)

FROM python:3.12-slim

WORKDIR /app

# Копируем из вашей backend-директории
COPY wegobackend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY wegobackend/ .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]